export const constants = {
    RESTAURANTS: 'restaurants',
    USER: 'user',
    MEDIUM: [
        { label: 'Email', value: 'email' },
        { label: 'Phone', value: 'phone' },
    ],
};

export const cities = [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Thane',
    'Nashik',
    'Kalyan-Dombivali',
    'Vasai-Virar',
    'Solapur',
    'Mira-Bhayandar',
    'Bhiwandi',
    'Amravati',
    'Nanded-Waghala',
    'Sangli',
    'Malegaon',
    'Akola',
    'Latur',
    'Dhule',
    'Ahmednagar',
    'Ichalkaranji',
    'Parbhani',
    'Panvel',
    'Yavatmal',
    'Achalpur',
    'Osmanabad',
    'Nandurbar',
    'Satara',
    'Wardha',
    'Udgir',
    'Aurangabad',
    'Amalner',
    'Akot',
    'Pandharpur',
    'Shrirampur',
    'Parli',
    'Washim',
    'Ambejogai',
    'Manmad',
    'Ratnagiri',
    'Uran Islampur',
    'Pusad',
    'Sangamner',
    'Shirpur-Warwade',
    'Malkapur',
    'Wani',
    'Lonavla',
    'Talegaon Dabhade',
    'Anjangaon',
    'Umred',
    'Palghar',
    'Shegaon',
    'Ozar',
    'Phaltan',
    'Yevla',
    'Shahade',
    'Vita',
    'Umarkhed',
    'Warora',
    'Pachora',
    'Tumsar',
    'Manjlegaon',
    'Sillod',
    'Arvi',
    'Nandura',
    'Vaijapur',
    'Wadgaon Road',
    'Sailu',
    'Murtijapur',
    'Tasgaon',
    'Mehkar',
    'Yawal',
    'Pulgaon',
    'Nilanga',
    'Wai',
    'Umarga',
    'Paithan',
    'Rahuri',
    'Nawapur',
    'Tuljapur',
    'Morshi',
    'Purna',
    'Satana',
    'Pathri',
    'Sinnar',
    'Uchgaon',
    'Uran',
    'Pen',
    'Karjat',
    'Manwath',
    'Partur',
    'Sangole',
    'Mangrulpir',
    'Risod',
    'Shirur',
    'Savner',
    'Sasvad',
    'Pandharkaoda',
    'Talode',
    'Shrigonda',
    'Shirdi',
    'Raver',
    'Mukhed',
    'Rajura',
    'Vadgaon Kasba',
    'Tirora',
    'Mahad',
    'Lonar',
    'Sawantwadi',
    'Pathardi',
    'Pauni',
    'Ramtek',
    'Mul',
    'Soyagaon',
    'Mangalvedhe',
    'Narkhed',
    'Shendurjana',
    'Patur',
    'Mhaswad',
    'Loha',
    'Nandgaon',
    'Warud',
];

export const homeCards = [
    {
        image: 'https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=1000',
        title: 'Order Online',
        description: 'Stay home and order at your doorstep',
        link: '/restaurants',
        type: 'online',
    },
    {
        image: 'https://images.pexels.com/photos/1579739/pexels-photo-1579739.jpeg?auto=compress&cs=tinysrgb&w=1000',
        title: 'Brunch Specials',
        description: "View city's favourite brunch venues",
        link: '/restaurants',
        type: 'brunch',
    },
    {
        image: 'https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg?auto=compress&cs=tinysrgb&w=1000',
        title: 'Dinner',
        description: "View city's favourite Dinner venues",
        link: '/restaurants',
        type: 'dinner',
    },
];

export const EXPLORE_OPTIONS = {
    one: [
        'Bakery food near me',
        'Beverages food near me',
        'Biryani food near me',
        'Burger food near me',
        'Chinese food near me',
        'Desserts food near me',
        'Ice Cream food near me',
        'Kebab food near me',
        'Maharashtrian food near me',
        'Momos food near me',
        'Mughlai food near me',
        'North Indian food near me',
        'Pizza food near me',
        'Rolls food near me',
        'Sandwich food near me',
        'Seafood food near me',
        'Shake food near me',
        'Sichuan food near me',
        'South Indian food near me',
        'Street food near me',
    ],
    two: [
        'Bakeries near me',
        'Bars near me',
        'Beverage Shops near me',
        'Bhojanalya near me',
        'Cafés near me',
        'Casual Dining near me',
        'Clubs near me',
        'Cocktail Bars near me',
        'Confectioneries near me',
        'Dessert Parlors near me',
        'Dhabas near me',
        'Fine Dining near me',
        'Food Courts near me',
        'Food Trucks near me',
        'Irani Cafes near me',
        'Kiosks near me',
        'Lounges near me',
        'Microbreweries near me',
        'Paan Shop near me',
        'Pubs near me',
        'Quick Bites near me',
        'Shacks near me',
        'Sweet Shops near me',
    ],
    three: [...cities],
};
